// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RetailPOS.Infrastructure.Persistence;

#nullable disable

namespace RetailPOS.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(LocalPosDbContext))]
    [Migration("20260704172839_AddLocalPersistenceModels")]
    partial class AddLocalPersistenceModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("RetailPOS.Infrastructure.Persistence.Entities.OrderEntity", b =>
                {
                    b.Property<Guid>("LocalOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("BusinessDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CashierId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DiscountAmount")
                        .HasPrecision(18)
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalOrderNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SubtotalAmount")
                        .HasPrecision(18)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TerminalId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18)
                        .HasColumnType("TEXT");

                    b.HasKey("LocalOrderId");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("LocalOrderNumber")
                        .IsUnique();

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("RetailPOS.Infrastructure.Persistence.Entities.OrderLineEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("GrossAmount")
                        .HasPrecision(18)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LineDiscountAmount")
                        .HasPrecision(18)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LineTotalAmount")
                        .HasPrecision(18)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LocalOrderId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LocalOrderId", "SortOrder")
                        .IsUnique();

                    b.ToTable("OrderLines", (string)null);
                });

            modelBuilder.Entity("RetailPOS.Infrastructure.Persistence.Entities.PaymentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApprovalCode")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ApprovedAmount")
                        .HasPrecision(18)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ApprovedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LocalOrderId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Method")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("RequestedAmount")
                        .HasPrecision(18)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TransactionReference")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LocalOrderId", "SortOrder")
                        .IsUnique();

                    b.ToTable("Payments", (string)null);
                });

            modelBuilder.Entity("RetailPOS.Infrastructure.Persistence.Entities.PendingCheckoutEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApprovalCode")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ApprovedAmount")
                        .HasPrecision(18)
                        .HasColumnType("TEXT");

                    b.Property<string>("CartSnapshotJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CashierId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PaymentApprovedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentSnapshotJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecoveryStatus")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TerminalId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RecoveryStatus", "CreatedAtUtc");

                    b.ToTable("PendingCheckouts", (string)null);
                });

            modelBuilder.Entity("RetailPOS.Infrastructure.Persistence.Entities.ProductEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Barcode")
                        .IsUnique();

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("RetailPOS.Infrastructure.Persistence.Entities.SyncQueueEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastErrorSummary")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NextAttemptAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferenceKey")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("RetryCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Status", "NextAttemptAtUtc", "CreatedAtUtc", "Id");

                    b.ToTable("SyncQueue", (string)null);
                });

            modelBuilder.Entity("RetailPOS.Infrastructure.Persistence.Entities.OrderLineEntity", b =>
                {
                    b.HasOne("RetailPOS.Infrastructure.Persistence.Entities.OrderEntity", "Order")
                        .WithMany("Lines")
                        .HasForeignKey("LocalOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("RetailPOS.Infrastructure.Persistence.Entities.PaymentEntity", b =>
                {
                    b.HasOne("RetailPOS.Infrastructure.Persistence.Entities.OrderEntity", "Order")
                        .WithMany("Payments")
                        .HasForeignKey("LocalOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("RetailPOS.Infrastructure.Persistence.Entities.OrderEntity", b =>
                {
                    b.Navigation("Lines");

                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
