// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RetailPOS.Infrastructure.Persistence;

#nullable disable

namespace RetailPOS.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(LocalPosDbContext))]
    [Migration("20260704165402_InitialLocalDatabase")]
    partial class InitialLocalDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");
#pragma warning restore 612, 618
        }
    }
}
